---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: rhoai-prometheus-grafanadatasource
spec:
  datasource:
      access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      name: RHOAI Prometheus
      type: prometheus
      url: {{ .Values.monitoring.prometheusUrl | quote }}
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
