---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/component: {{ .Values.app }}
    app.kubernetes.io/instance: {{ .Values.app }}
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    monitoring.opendatahub.io/scrape: 'true'
    app.openshift.io/runtime: python
spec:
  replicas: 1
  server:
    userConfig:
      # reference to the configmap that contains Llama stack configuration.
      configMapName: {{ .Values.app }}-run
    containerSpec:
      env:
        {{- $appName := .Values.app }}
        {{- $allModels := (include "allModels" $ | fromYaml).items }}
        {{- range $allModels }}
        - name: {{ include "rag-lsd.envVarName" .name }}_MODEL
          valueFrom:
            secretKeyRef:
              key: {{ include "rag-lsd.envVarName" .name }}_MODEL
              name: {{ $appName }}-secret
        - name: {{ include "rag-lsd.envVarName" .name }}_URL
          valueFrom:
            secretKeyRef:
              key: {{ include "rag-lsd.envVarName" .name }}_URL
              name: {{ $appName }}-secret
        {{- if .api_token }}
        - name: {{ include "rag-lsd.envVarName" .name }}_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: {{ include "rag-lsd.envVarName" .name }}_API_TOKEN
              name: {{ $appName }}-secret
        {{- end }}
        {{- if .tls_verify }}
        - name: {{ include "rag-lsd.envVarName" .name }}_TLS_VERIFY
          valueFrom:
            secretKeyRef:
              key: {{ include "rag-lsd.envVarName" .name }}_TLS_VERIFY
              name: {{ $appName }}-secret
        {{- end }}
        {{- if .max_tokens }}
        - name: {{ include "rag-lsd.envVarName" .name }}_MAX_TOKENS
          valueFrom:
            secretKeyRef:
              key: {{ include "rag-lsd.envVarName" .name }}_MAX_TOKENS
              name: {{ $appName }}-secret
        {{- end }}
        {{- end }}
        {{- if .Values.postgres }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres.host | default "pg-lsd-service" | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.port | default 5432 | quote }}
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-lsd-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-lsd-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-lsd-secret
              key: POSTGRES_PASSWORD
        {{- if .Values.postgres.enablePgVector }}
        - name: ENABLE_PGVECTOR
          value: {{ .Values.postgres.enablePgVector | default false | quote }}
        - name: PGVECTOR_HOST
          value: {{ .Values.postgres.host | default "pg-lsd-service" | quote }}
        - name: PGVECTOR_PORT
          value: {{ .Values.postgres.port | default 5432 | quote }}
        - name: PGVECTOR_DB
          valueFrom:
            secretKeyRef:
              name: pgvector-lsd-secret
              key: PGVECTOR_DB
        - name: PGVECTOR_USER
          valueFrom:
            secretKeyRef:
              name: pgvector-lsd-secret
              key: PGVECTOR_USER
        - name: PGVECTOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgvector-lsd-secret
              key: PGVECTOR_PASSWORD
        {{- end}}
        {{- end }}
        {{- if and .Values.milvus .Values.milvus.enableRemote }}
        - name: ENABLE_MILVUS
          value: {{ .Values.milvus.enableRemote | quote }}
        - name: MILVUS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_ENDPOINT
        - name: MILVUS_TOKEN
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_TOKEN
        - name: MILVUS_SECURE
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_SECURE
        - name: MILVUS_CONSISTENCY_LEVEL
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_CONSISTENCY_LEVEL
        - name: MILVUS_CA_PEM_PATH
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_CA_PEM_PATH
        - name: MILVUS_CLIENT_PEM_PATH
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_CLIENT_PEM_PATH
        - name: MILVUS_CLIENT_KEY_PATH
          valueFrom:
            secretKeyRef:
              name: milvus-remote-secret
              key: MILVUS_CLIENT_KEY_PATH
        {{- end }}
        - name: MILVUS_DB_PATH
          value: {{ .Values.milvusDbPath | quote }}
        - name: FMS_ORCHESTRATOR_URL
          value: {{ .Values.fmsOchestratorUrl | quote }}
        {{- if .Values.otelCollector.enabled }}
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.app }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otelCollector.endpoint | quote }}
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: {{ .Values.otelCollector.protocol | quote }}
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: {{ .Values.otelCollector.tracesEndpoint | quote }}
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: {{ .Values.otelCollector.metricsEndpoint | quote }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ .Values.otelCollector.resourceAttributes | quote }}
        - name: OTEL_SERVICE_VERSION
          value: {{ .Values.otelCollector.serviceVersion | quote }}
        - name: OTEL_DEPLOYMENT_ENVIRONMENT
          value: {{ .Values.otelCollector.deploymentEnvironment | quote }}
        - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
          value: {{ .Values.otelCollector.pythonDisabledInstrumentations | quote }}
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: {{ .Values.otelCollector.pythonLoggingAutoInstrumentationEnabled | quote }}
        - name: OTEL_BSP_MAX_QUEUE_SIZE
          value: {{ .Values.otelCollector.bspMaxQueueSize | quote }}
        - name: OTEL_BSP_SCHEDULE_DELAY
          value: {{ .Values.otelCollector.bspScheduleDelay | quote }}
        - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
          value: {{ .Values.otelCollector.bspMaxExportBatchSize | quote }}
        - name: OTEL_BSP_EXPORT_TIMEOUT
          value: {{ .Values.otelCollector.bspExportTimeout | quote }}
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: {{ .Values.otelCollector.metricExportInterval | quote }}
        - name: TELEMETRY_SINKS
          value: {{ .Values.otelCollector.telemetrySinks | quote }}
        {{- end }}
        
      name: llama-stack
      port: {{ .Values.lsdPort | default 8321 }}
      {{- if .Values.lsdResources }}
      resources:
        {{- if .Values.lsdResources.limits }}
        limits:
          cpu: {{ .Values.lsdResources.limits.cpu | default "2" }}
          memory: {{ .Values.lsdResources.limits.memory | default "12Gi" }}
        {{- end }}
        {{- if .Values.lsdResources.requests }}
        requests:
          cpu: {{ .Values.lsdResources.requests.cpu | default "250m" }}
          memory: {{ .Values.lsdResources.requests.memory | default "1Gi" }}
        {{- end }}
      {{- end }}
    distribution:
      {{- if .Values.lsdName }}
      name: '{{ .Values.lsdName | default "rh-dev"}}'
      {{- else }}
      image: '{{ .Values.lsdImage }}'
      {{- end }}
    storage:
      size: 5Gi
      {{- if .Values.lsdMountPath }}
      mountPath: {{ .Values.lsdMountPath }}
      {{- end }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.app }}-route"
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.routeTimeout | default "1m" | quote }}
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: "{{ .Values.app }}-service"
    weight: 100
  wildcardPolicy: None